In [1]:
#Importando biblioteca
import pandas as pd
import numpy as np

In [3]:
#Importando a primeira base
df = pd.read_csv(r'/content/drive/MyDrive/Trabalhos e testes em python/dbb-teste-analista.csv', encoding='UTF-8', sep=';')

In [4]:
#Importando a segunda base
df_1 = pd.read_csv(r'/content/drive/MyDrive/Trabalhos e testes em python/dba-teste-analista (1).csv',encoding='ISO-8859-1', sep = ";")

In [5]:
#Listando as colunas da primeira base
print(list(df.columns))

['create_full', 'Data_Nascimento', 'onboarding_state', 'Onboard_status', 'Onboard_status_index', 'Gender', 'Geolocation-Latitude', 'Geolocation-Longitude', 'Situacao_Cadastral', 'assets_range', 'income', 'home_address_country', 'home_address_state', 'home_address_city', 'commercial_address_country', 'commercial_address_state', 'commercial_address_city', 'verified_mobile', 'Document_valid', 'Estado_Civil', 'VerifiedEmail']

In [6]:
#Listando as colunas da segunda base
print(list(df_1.columns))

['onboarding_state', 'Onboard_status', 'Onboard_status_index']

In [7]:
#Verificando o tamanho do primeiro Dataframe
df.shape

(1000, 21)

In [8]:
#Verificando o quandidade de cadastros de usurarios criados
df.create_full.nunique()

1000

In [9]:
#Como os usuarios são unicos, vou criar uma lista de ids para facilitar a vizualizção na criação das chaves primárias
df['Id'] = list(range(1 ,len(df)+1))
df.Id = df.Id.astype(int)
df

,create_full,Data_Nascimento,onboarding_state,Onboard_status,Onboard_status_index,Gender,Geolocation-Latitude,Geolocation-Longitude,Situacao_Cadastral,assets_range,...,home_address_state,home_address_city,commercial_address_country,commercial_address_state,commercial_address_city,verified_mobile,Document_valid,Estado_Civil,VerifiedEmail,Id
0,2021-02-16T21:33:09.5116639Z,17/11/1982,32005.0,NaN,NaN,MALE,-168.122.774,-493.082.998,REGULAR,101k-200k,...,GO,Aparecida de Goiânia,NaN,NaN,NaN,True,True,MARRIED,True,1
1,2020-05-18T14:48:37.3329941Z,07/09/1980,32004.0,NaN,NaN,MALE,-296.499.084,-507.822.685,REGULAR,201k-500k,...,RS,Parobé,BRA,RS,Taquara,True,True,MARRIED,True,2
2,2020-11-04T01:59:27.5273914Z,08/10/1983,32005.0,NaN,NaN,MALE,-166.581.826,-492.791.379,REGULAR,51k-100k,...,GO,Trindade,NaN,NaN,NaN,True,True,MARRIED,True,3
3,2021-02-07T17:58:16.8274624Z,16/05/1982,32005.0,NaN,NaN,MALE,-25.602.437,-441.820.335,REGULAR,101k-200k,...,MA,São José de Ribamar,NaN,NaN,NaN,True,True,MARRIED,True,4
4,2021-01-27T09:38:21.3406464Z,15/01/1981,32003.0,NaN,NaN,FEMALE,-37.084.048,-403.348.748,REGULAR,0-25k,...,CE,Sobral,NaN,NaN,NaN,True,True,SINGLE,True,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2021-01-21T14:06:04.6097124Z,14/05/1978,32003.0,NaN,NaN,FEMALE,-58.471.977,-352.569.786,REGULAR,51k-100k,...,RN,Natal,NaN,NaN,NaN,True,True,SINGLE,True,996
996,2020-05-15T17:48:36.7354256Z,01/05/1987,32003.0,NaN,NaN,MALE,-29.898.216.550.294.000,-5.121.833.115.947.900,IRREGULAR,0-25k,...,RS,Canoas,NaN,NaN,NaN,True,False,MARRIED,True,997
997,2021-02-04T03:46:04.8712646Z,08/04/1984,32005.0,NaN,NaN,MALE,-123.036.433,-38.949.523,REGULAR,51k-100k,...,BA,Feira de Santana,NaN,NaN,NaN,True,True,SINGLE,True,998
998,2021-02-14T03:50:54.4372518Z,11/09/1979,32005.0,NaN,NaN,MALE,-198.731.564,-43.922.925,REGULAR,201k-500k,...,MG,Belo Horizonte,NaN,NaN,NaN,True,True,MARRIED,True,999
999,2021-02-28T18:07:33.4242893Z,27/03/1984,32005.0,NaN,NaN,MALE,-159.103.645,-48.053.343,REGULAR,0-25k,...,DF,Brasília,NaN,NaN,NaN,True,True,SINGLE,True,1000

In [10]:
#Verifiando os tipos de dados do Dataframe e tamanho do arquivo
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   create_full                 1000 non-null   object
 1   Data_Nascimento             1000 non-null   object
 2   onboarding_state            1000 non-null   float64
 3   Onboard_status              0 non-null      float64
 4   Onboard_status_index        0 non-null      float64
 5   Gender                      1000 non-null   object
 6   Geolocation-Latitude        1000 non-null   object
 7   Geolocation-Longitude       1000 non-null   object
 8   Situacao_Cadastral          1000 non-null   object
 9   assets_range                995 non-null    object
 10  income                      999 non-null    float64
 11  home_address_country        1000 non-null   object
 12  home_address_state          1000 non-null   object
 13  home_address_city           1000 non-null   object
 14  commercial_address_country  169 non-null    object
 15  commercial_address_state    169 non-null    object
 16  commercial_address_city     169 non-null    object
 17  verified_mobile             1000 non-null   bool
 18  Document_valid              1000 non-null   bool
 19  Estado_Civil                1000 non-null   object
 20  VerifiedEmail               1000 non-null   bool
 21  Id                          1000 non-null   int64
dtypes: bool(3), float64(4), int64(1), object(14)
memory usage: 151.5+ KB

In [11]:
#Criando um dataframe que mescle as duas bases de dados com o onboarding_state e completando o os dados que não estão na tabela
base_collumn = ['Id', 'onboarding_state', 'Onboard_status', 'Onboard_status_index' ]
df_status_1 = df[base_collumn]

df_status = pd.merge(df_status_1, df_1 , how= 'inner', on= ['onboarding_state']) #mesclando as duas base no valor em comum
df_status = df_status.drop(columns={'Onboard_status_x', 'Onboard_status_index_x'}) #Dropando as colunas repetidas
df_status.rename(columns={'Onboard_status_y': 'Onboard_status', 'Onboard_status_index_y' : 'Onboard_status_index' } , inplace= True) #Renomeando as colunas
df_status

       Id  onboarding_state      Onboard_status  Onboard_status_index
0       1           32005.0  Aprovado sem Conta                     5
1       2           32004.0           Rejeitado                     4
2       3           32005.0  Aprovado sem Conta                     5
3       4           32005.0  Aprovado sem Conta                     5
4       5           32003.0  Aprovado com Conta                     6
..    ...               ...                 ...                   ...
995   996           32003.0  Aprovado com Conta                     6
996   997           32003.0  Aprovado com Conta                     6
997   998           32005.0  Aprovado sem Conta                     5
998   999           32005.0  Aprovado sem Conta                     5
999  1000           32005.0  Aprovado sem Conta                     5

[1000 rows x 4 columns]

In [12]:
#Verificando os valores
df.verified_mobile.value_counts()

verified_mobile
True     997
False      3
Name: count, dtype: int64

In [13]:
#Verificando os valores
df.Document_valid.value_counts()

Document_valid
True     991
False      9
Name: count, dtype: int64

In [14]:
#Verificando os valores
df.Estado_Civil.value_counts()

Estado_Civil
SINGLE      594
MARRIED     278
DIVORCED     63
AMASSED      40
WIDOWED      10
AMASSAED      6
SINGLES       5
WIDOWER       4
Name: count, dtype: int64

In [15]:
#Verificando os valores
df.Gender.value_counts()

Gender
MALE      700
FEMALE    292
MALEE       8
Name: count, dtype: int64

In [ ]:
#Verificando os valores
df.VerifiedEmail.value_counts()

VerifiedEmail
True     997
False      3
Name: count, dtype: int64

In [ ]:
base_columns = ['Id', 'Gender' ,'verified_mobile', 'Document_valid', 'Estado_Civil','VerifiedEmail' , 'Situacao_Cadastral' ]
df_demografico = df[base_columns]

def resp(x):
    if x == True:
        return 'Sim'
    elif x == False:
        return 'Não'

def estadocivil(x):    #Função para corrigir os valores de Estado civil
    if x == 'SINGLE':
        return 'Solteiro'
    elif x == 'SINGLES':
        return 'Solteiro'
    elif x == 'MARRIED':
        return 'Casado'
    elif x == 'AMASSED':
        return 'União Estável'
    elif x == 'AMASSAED ':
        return 'União Estável'
    elif x == 'DIVORCED':
        return 'Divorciado'
    else:
        return 'Viuvo'

def genero(x):
    if x == 'FEMALE':
      return 'Mulher'
    else:
      return 'Homem'

df_demografico.loc[:, 'Document_valid'] = df_demografico['Document_valid'].apply(resp)   #Aplicando as funções
df_demografico.loc[:, 'verified_mobile'] = df_demografico['verified_mobile'].apply(resp)
df_demografico.loc[:, 'Estado_Civil'] = df_demografico['Estado_Civil'].apply(estadocivil)
df_demografico.loc[:, 'VerifiedEmail'] = df_demografico['VerifiedEmail'].apply(resp)
df_demografico.loc[:, 'Gender'] = df_demografico['Gender'].apply(genero)


df_demografico

In [24]:
#Criando um dataframe para os endereços informados
base_home = ['Id']
second_home = [x for x in df.columns if x.startswith('home')]   #Primeiro crio um somente com os endereços residenciais
df_home = df[base_home + second_home].copy()
df_home.loc[:, 'Tipo'] = "Residencial"
df_home.rename(columns={'home_address_country': 'País', 'home_address_state': 'Estado', 'home_address_city': 'Cidade'}, inplace=True)

base_comercial = ['Id']
second_comercial = [x for x in df if x.startswith('commercial')]  #Segundo crio um somente com os endereços comerciais
df_comercial = df[base_comercial+second_comercial].copy()
df_comercial.loc[:, 'Tipo'] = "Comercial"
df_comercial.rename(columns={'commercial_address_country': 'País',
                              'commercial_address_state' :'Estado', 'commercial_address_city' : 'Cidade'}, inplace= True)

dict_estados = {'AC': 'Acre', 'AM': 'Amazonas', 'AL': 'Alagoas' , 'AP': 'Amapá', 'BA': 'Bahia', 'CE': 'Ceará', 'DF': 'Distrito Federal',
                'ES' : 'Espírito Santos', 'GO': 'Goiás', 'MA': 'Maranhão', 'MG': 'Minas Gerais', 'MS' :'Mato Grosso do Sul', 'MT': 'Mato Grosso', 'PA': 'Pará',
                'PB': 'Paraíba', 'PE':'Pernambuco'  , 'PI': 'Piauí' , 'PR': 'Paraná', 'RJ' : 'Rio de Janeiro' , 'RN' : 'Rio Grande do Norte',
                'RO' : 'Rondônia', 'RR': 'Rorâima', 'RS' : 'Rio Grande do Sul', 'SC': 'Santa Catarina', 'SE': 'Sergipe', 'SP' : 'São Paulo' , 'TO': 'Tocantins'}

df_enderecos = pd.concat([df_home,df_comercial]).dropna()  #Ao final concateno as duas bases
df_enderecos.Estado = df_enderecos.Estado.map(dict_estados) #Aplico o dicionário criado
df_enderecos

      Id País             Estado                Cidade         Tipo
0      1  BRA              Goiás  Aparecida de Goiânia  Residencial
1      2  BRA  Rio Grande do Sul                Parobé  Residencial
2      3  BRA              Goiás              Trindade  Residencial
3      4  BRA           Maranhão   São José de Ribamar  Residencial
4      5  BRA              Ceará                Sobral  Residencial
..   ...  ...                ...                   ...          ...
968  969  BRA              Bahia              Salvador    Comercial
969  970  BRA             Paraná               Pinhais    Comercial
973  974  BRA             Paraná          Ponta Grossa    Comercial
982  983  BRA              Ceará             Fortaleza    Comercial
983  984  BRA               Pará              Santarém    Comercial

[1169 rows x 5 columns]

In [25]:
#Verificando os resultados após a concatenação
df_enderecos.Tipo.value_counts()

Tipo
Residencial    1000
Comercial       169
Name: count, dtype: int64

In [28]:
df_enderecos.Estado.value_counts()

Estado
Paraná                 162
Bahia                  110
Rio Grande do Sul      103
Goiás                  100
Santa Catarina          80
Rio de Janeiro          66
Ceará                   65
Pará                    61
São Paulo               50
Distrito Federal        49
Minas Gerais            41
Amazonas                37
Maranhão                33
Rondônia                24
Rio Grande do Norte     24
Mato Grosso             21
Pernambuco              20
Piauí                   19
Sergipe                 19
Alagoas                 16
Mato Grosso do Sul      15
Paraíba                 15
Espírito Santos         13
Amapá                    9
Acre                     8
Tocantins                7
Rorâima                  2
Name: count, dtype: int64

In [29]:

base_collumn = ['Id','Geolocation-Latitude', 'Geolocation-Longitude']
df_localizao = df[base_collumn]


df_localizao

       Id     Geolocation-Latitude   Geolocation-Longitude
0       1             -168.122.774            -493.082.998
1       2             -296.499.084            -507.822.685
2       3             -166.581.826            -492.791.379
3       4              -25.602.437            -441.820.335
4       5              -37.084.048            -403.348.748
..    ...                      ...                     ...
995   996              -58.471.977            -352.569.786
996   997  -29.898.216.550.294.000  -5.121.833.115.947.900
997   998             -123.036.433             -38.949.523
998   999             -198.731.564             -43.922.925
999  1000             -159.103.645             -48.053.343

[1000 rows x 3 columns]

In [30]:
#Verificando a lista de valores de assets_range
set(df.assets_range)

{'0-25k',
 '1.1kk-10kk',
 '101k-200k',
 '10kk-100kkk',
 '201k-500k',
 '26k-50k',
 '501k-1kk',
 '51k-100k',
 '51k-100ks',
 nan}

In [31]:
#Os assests_range não são compativeis com o income
df.query("assets_range ==  '1.1kk-10kk'").income

24     1500001.0
213    1500001.0
236    1500001.0
265    4000000.0
272    1000001.0
325     750001.0
358     750001.0
422    1500001.0
445    1000000.0
585    1500001.0
593    1500001.0
712     250001.0
756    1500001.0
766    1500001.0
896    1500001.0
Name: income, dtype: float64

In [32]:
#Corrigir porque tem rendas que não batem com que foi informado de patrimonio
base_collumn = ['Id', 'Situacao_Cadastral', 'assets_range', 'income']
df_cadastro_renda = df[base_collumn]

df_cadastro_renda['income'] = pd.to_numeric(df_cadastro_renda['income'], errors='coerce')  # Converter para numérico, forçando NA para valores inválidos
df_cadastro_renda['income'].fillna(0, inplace=True)  # Substituir NA por 0 ou outro valor apropriado
df_cadastro_renda['income'] = df_cadastro_renda['income'].astype(int)  # Converter para int
def renda(x):
  if x in range(0,26000):
    return '0-25 mil'
  elif x in range(26000,51000):
    return '26 -50 mil'
  elif x in range(51000,101000):
    return '51-100 mil'
  elif x in range(101000,201000):
    return '101-200 mil'
  elif x in range(201000,501000):
    return '201-500 mil'
  elif x in range(501000,1100000):
    return '501 mil -1 milhão'
  elif x in range(1100000,10000000):
    return '1,1-10 milhões'
  else:
    return '10-100 milhões'


df_cadastro_renda['Renda'] = df_cadastro_renda.income.apply(renda)
df_cadastro_renda

/tmp/ipython-input-2800995503.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cadastro_renda['income'] = pd.to_numeric(df_cadastro_renda['income'], errors='coerce')  # Converter para numérico, forçando NA para valores inválidos
/tmp/ipython-input-2800995503.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cadastro_renda['income'].fillna(0, inplace=True)  # Substituir NA por 0 ou outro valor apropriado
/tmp/ipython-input-2800995503.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cadastro_renda['income'].fillna(0, inplace=True)  # Substituir NA por 0 ou outro valor apropriado
/tmp/ipython-input-2800995503.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cadastro_renda['income'] = df_cadastro_renda['income'].astype(int)  # Converter para int
/tmp/ipython-input-2800995503.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cadastro_renda['Renda'] = df_cadastro_renda.income.apply(renda)

       Id Situacao_Cadastral assets_range  income              Renda
0       1            REGULAR    101k-200k  250000        201-500 mil
1       2            REGULAR    201k-500k  420800        201-500 mil
2       3            REGULAR     51k-100k  250001        201-500 mil
3       4            REGULAR    101k-200k  500001        201-500 mil
4       5            REGULAR        0-25k  250000        201-500 mil
..    ...                ...          ...     ...                ...
995   996            REGULAR     51k-100k  250001        201-500 mil
996   997          IRREGULAR        0-25k    3000           0-25 mil
997   998            REGULAR     51k-100k  500001        201-500 mil
998   999            REGULAR    201k-500k  750001  501 mil -1 milhão
999  1000            REGULAR        0-25k  250001        201-500 mil

[1000 rows x 5 columns]

In [33]:
df_cadastro_renda.Renda.value_counts()

Renda
201-500 mil          797
501 mil -1 milhão    121
1,1-10 milhões        50
101-200 mil           13
0-25 mil              13
10-100 milhões         6
Name: count, dtype: int64

In [34]:
df.Data_Nascimento.value_counts()

Data_Nascimento
01/07/1982    3
04/10/1985    3
11/07/1983    3
18/12/1984    3
10/09/1984    3
             ..
20/07/1981    1
12/10/1968    1
18/05/1967    1
16/08/1981    1
01/03/1974    1
Name: count, Length: 936, dtype: int64

In [36]:
from datetime import datetime
base_collumn = ['Id' , 'Data_Nascimento']
df_idade = df[base_collumn]
df_idade['Data_Nascimento'] = df_idade['Data_Nascimento'].replace('1083-08-27', '27/08/1983') # tive que corrigir na mão esse valor
df_idade['Data_Nascimento'] = df_idade['Data_Nascimento'].replace("0001-01-01", '01/01/2000') # tive que corrigir na mão esse valor
df_idade['Data_Nascimento'] = pd.to_datetime(df_idade['Data_Nascimento'], format='%d/%m/%Y')  #  Padronizei as datas
data_ref = pd.Timestamp('2024-06-14') #data de quando montei
df_idade['Idade'] = df_idade['Data_Nascimento'].apply(lambda x: data_ref.year - x.year - ((data_ref.month, data_ref.day) < (x.month, x.day))).astype(int)
def faixa(x):
  if x in range(0,19):
    return "Até 18 anos"
  elif x in range(19,31):
    return '19 a 30 anos'
  elif x in range(31,46):
    return '30 a 45 anos'
  else:
    return 'Acima de 45 anos'
df_idade['Faixa etária'] = df_idade.Idade.apply(faixa)
df_idade

/tmp/ipython-input-218602847.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_idade['Data_Nascimento'] = df_idade['Data_Nascimento'].replace('1083-08-27', '27/08/1983') # tive que corrigir na mão esse valor
/tmp/ipython-input-218602847.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_idade['Data_Nascimento'] = df_idade['Data_Nascimento'].replace("0001-01-01", '01/01/2000') # tive que corrigir na mão esse valor
/tmp/ipython-input-218602847.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_idade['Data_Nascimento'] = pd.to_datetime(df_idade['Data_Nascimento'], format='%d/%m/%Y')  #  Padronizei as datas
/tmp/ipython-input-218602847.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_idade['Idade'] = df_idade['Data_Nascimento'].apply(lambda x: data_ref.year - x.year - ((data_ref.month, data_ref.day) < (x.month, x.day))).astype(int)
/tmp/ipython-input-218602847.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_idade['Faixa etária'] = df_idade.Idade.apply(faixa)

       Id Data_Nascimento  Idade      Faixa etária
0       1      1982-11-17     41      30 a 45 anos
1       2      1980-09-07     43      30 a 45 anos
2       3      1983-10-08     40      30 a 45 anos
3       4      1982-05-16     42      30 a 45 anos
4       5      1981-01-15     43      30 a 45 anos
..    ...             ...    ...               ...
995   996      1978-05-14     46  Acima de 45 anos
996   997      1987-05-01     37      30 a 45 anos
997   998      1984-04-08     40      30 a 45 anos
998   999      1979-09-11     44      30 a 45 anos
999  1000      1984-03-27     40      30 a 45 anos

[1000 rows x 4 columns]

In [ ]:
from google.colab import files
df_status.to_csv('status.csv', encoding='UTF-8', sep=';', index= False )
df_demografico.to_csv('demografico.csv', encoding='UTF-8', sep=';', index= False )
df_enderecos.to_csv('enderecos.csv', encoding='UTF-8', sep=';', index= False )
df_localizao.to_csv('localizacao.csv', encoding='UTF-8', sep=';', index= False )
df_cadastro_renda.to_csv('renda.csv', encoding='UTF-8', sep=';', index= False )
df_idade.to_csv('idade.csv', encoding='UTF-8', sep=';', index= False )
files.download('status.csv')
files.download('demografico.csv')
files.download('enderecos.csv')
files.download('localizacao.csv')
files.download('renda.csv')
files.download('idade.csv')